-   hosts: server
    vars_files:
        -   ../ansible_secret.yml
    vars:
        root_dir: '/var/tmp/www'
        nginx_port: '8080'
    tasks:
    -   name: install nginx
        ansible.builtin.apt:
            name: nginx
            state: latest
        become: yes

    -   name: create root dir
        ansible.builtin.file:
            path: "{{ root_dir }}"
            state: directory
            recurse: yes
            mode: '0755'

    -   name: copy index
        ansible.builtin.copy:
            src: files/index.html
            dest: "{{ root_dir }}/index.html"
        become: yes

    -   name: copy nginx config
        ansible.builtin.template:
            src: templates/nginx.conf.j2
            dest: /etc/nginx/nginx.conf
        notify:
            -   restart nginx
        become: yes

    handlers:
    -   name: restart nginx
        ansible.builtin.service:
            name: nginx
            state: reloaded
        become: yes
